// packages
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

// components
import { ToastProvider } from "@/components/providers/toaster-provider";

// css
import TopLoaderProvider from "@/components/providers/TopLoaderProvider";
import { ConfettiProvider } from "@/components/providers/confetti-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <ConfettiProvider />
                    <ToastProvider />
                    <TopLoaderProvider />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
